dist: xenial
language: python
sudo: false
addons:
  postgresql: 9.6
  apt:
    packages:
      - postgresql-9.6-postgis-2.4
python: 3.7
install: 
  - pip install poetry
  - poetry install
notifications:
    email:
        - james@openstates.org
jobs:
  include:
    - stage: test
      script: flake8 scripts
      name: "Flake8 Python"
    - script: ./scripts/run_tests.sh
      env:
        - PYTHONPATH=scripts
      name: "Test Python"
      before_script:
        - psql -c "CREATE USER openstates with PASSWORD 'openstates' CREATEDB SUPERUSER;" -U postgres
        - psql -c "CREATE DATABASE testdb;" -U postgres
        - psql -c "CREATE EXTENSION postgis;" -U postgres -d testdb
      after_success:
        - coveralls
    - script: ./scripts/lint_yaml.py
      name: "Check YAML"
