language: python
sudo: false
python: 3.6
install: pip install -r scripts/requirements.txt
notifications:
    email:
        - james@openstates.org
jobs:
  include:
    - stage: test
      script: flake8 scripts
      name: "Flake8 Python"
    - script: ./scripts/run_tests.sh
      env:
        - PYTHONPATH=scripts
      name: "Test Python"
    # - script: ./scripts/check_yaml.py
    #   name: "Check YAML"
