[tool.poetry]
name = "openstates-people"
version = "1.3"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.7"
yamlordereddictloader = "^0.4.0"
click = "^7.0"
opencivicdata = "^2.4"
Django = "^2.2"
PyYAML = "^5.1"
boto3 = "^1.9"
pillow = "^6.1"

[tool.poetry.dev-dependencies]
flake8 = "^3.7"
pytest = "^5.1"
pytest-django = "^3.5"
pytest-cov = "^2.7"
coveralls = "^1.8"

[tool.black]
line-length = 99
py36 = true
exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | build
  | dist
)/
'''
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

