# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test Scripts & Lint YAML

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRS_USER: 'openstates'
          POSTGRES_PASSWORD: 'openstates'
          POSTGRES_DB: 'testdb'
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: setup Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: install Poetry
      uses: dschep/install-poetry-action@v1.3
    - name: cache Poetry virtualenv
      uses: actions/cache@v2
      id: cache
      with:
        path: ~/.virtualenvs/
        key: poetry-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          poetry-${{ hashFiles('**/poetry.lock') }}
    - name: set poetry config path
      run: poetry config virtualenvs.path ~/.virtualenvs
    - name: install dependencies
      run: poetry install
      if: steps.cache.outputs.cache-hit != 'true'
     
    - name: lint with flake8
      run: poetry run flake8  scripts --show-source --statistics
    - name: pytest
      run: poetry run ./scripts/run_tests.sh
      env: 
        PYTHONPATH: scripts
        POSTGRES_HOST: postgres
    - name: lint yaml
      run: poetry run ./scripts/lint_yaml.py
      env: 
        PYTHONPATH: scripts
